### ISSUE TITLE
Error while using it inside node 10

### ISSUE THREAD

**Issue by tusharmath** [evanw/node-source-map-support#214] opened 2018-04-27 08:08 UTC
I get this error when I use `mocha --require=node-ts/register`

<details>
  <summary>Stack Trace</summary>
internal/util.js:360
    const filename = frame.getFileName();
                           ^
TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at Array.<anonymous> (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:163:21)
    at /Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:185:21)
    at wrapCallSite (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:357:20)
    at /Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:392:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:391:24)
    at /Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/reporters/base.js:195:21
    at Array.forEach (<anonymous>)
    at Function.exports.list (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/reporters/base.js:178:12)
    at Min.Base.epilogue (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/reporters/base.js:350:10)
    at Runner.emit (events.js:187:15)
    at /Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/runner.js:829:12
    at done (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/runner.js:666:7)
    at Runner.next [as nextSuite] (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/runner.js:633:16)
    at Runner.uncaught (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/runner.js:754:17)
    at process.uncaught (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/mocha/lib/runner.js:821:10)
    at process.emit (events.js:182:13)
    at process.emit (/Users/tushar/Documents/Projects/mobile-web-dream11/node_modules/source-map-support/source-map-support.js:453:21)
    at process._fatalException (internal/bootstrap/node.js:435:27)

</details>

**Comment by LinusU** [comment] 2018-04-27 08:32
Duplicate of #213 

> Sorry, I used `v0.4.18`. It's fixed in `v0.5.5`.

**Closed by LinusU** 2018-04-27 08:32 UTC
